channels: 
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - opencv
  - transformers
  - accelerate
  - datasets
  - imagehash
  - scikit-learn
  - scipy
  - jupyter
  - openai
  - pydantic
  - pip:
    - kernels==0.14.1