name: flowsis
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - einops
  - h5py
  - loguru
  - numpy
  - matplotlib
  - pandas
  - plotly
  - pytorch
  - torchvision
  - requests
  - tabulate
  - tensorboard
  - transformers
  - accelerate
  - datasets
  - imagehash
  - scikit-learn
  - scipy
  - jupyter
  - openai
  - pydantic
  - lightning
  - timm
  - pypng
  - pytest
  - black
  - pip:
    - kernels==0.14.1
    - kaleido
    - opencv-python
    - ptlflow==0.4.2
